### ISSUE TITLE
Get access to Google Analytics (or get a new account)

### ISSUE THREAD

**Issue by nicolasmccurdy** [rit-sse/crazy-train#24]

**Comment by kristenmills** [comment]
Has this been fixed?

**Comment by kristenmills** [comment]
@codykrieger has the old one.  But we can just make a new one if that hasn't been done yet.

**Comment by codykrieger** [comment]
I'm not sure I can transfer the existing one to another Google account, but if it's possible, I'll happily do so.

**Comment by nicolasmccurdy** [comment]
You can share a Google analytics property with other accounts, I assume/hope that you can use this to make someone else an admin and transfer the property to their account.

**Comment by codykrieger** [comment]
Indeed, that seems to be the case...what email(s) should I add as admins?

**Comment by kristenmills** [comment]
kristen@kristen-mills.com for now.  Thanks Cody!

**Comment by codykrieger** [comment]
Done!

**Comment by kristenmills** [comment]
Sweet deal. I'm closing this.
