### ISSUE TITLE
Map link is inaccurate

### ISSUE THREAD

**Issue by nickmccurdy** [rit-sse/crazy-train#30]
__Page:__ [About the SSE](https://sse.se.rit.edu/about/)
__Link:__ [(GOL-1670)](http://maps.rit.edu/?zoom=17&lat=43.)

**Comment by BillDybas** [comment]
**[This](https://maps.rit.edu/?zoom=20&lat=43.08384053670899&lng=-77.67983857233527)** seems more appropriate.

**Comment by nicolasmccurdy** [comment]
Bump
