### ISSUE TITLE
Certificate issues

### ISSUE THREAD

**Issue by nicolasmccurdy** [rit-sse/crazy-train#33]
Browsers Affected
---

### [SSE Site](http://sse.se.rit.edu)
| Browser  | Windows | Mac OS |
| --- | --- | --- |
| Chrome | untrusted | trusted |
| Firefox  | trusted | untrusted |
| Internet Explorer | trusted | |
| Opera | trusted | trusted |
| Safari | | trusted |

### [SSE Mail](http://mail.ad.sofse.org)
| Browser  | Windows | Mac OS |
| --- | --- | --- |
| Chrome | untrusted | untrusted |
| Firefox  | untrusted | untrusted |
| Internet Explorer | untrusted | |
| Opera | untrusted | untrusted |
| Safari | | untrusted |

Error messages
---

Moved to an [imgur album](http://imgur.com/a/DkWqR) to make the screenshots easier to navigate.

**Comment by kristenmills** [comment]
This is no longer an issue
